#!/usr/bin/env python3
"""
Generate Hugo data files from the spreadsheets in data-src/.

    python3 scripts/build_data.py            # regenerate data/*.yaml
    python3 scripts/build_data.py --check    # verify they are current, write nothing

WHY THE CSVs CANNOT SIMPLY LIVE IN data/.

Hugo does not load CSV into `.Site.Data`. It reads the file, finds a
`[][]string` where it wants a map, logs

    ERROR unexpected data type [][]string in file working-papers.csv

and puts NOTHING under that key. That failure is quiet in the worst way:
`{{ with index .Site.Data "working-papers" }}` sees an empty value, takes the
else branch, and the section renders as though there were no working papers.
No error on the page, no missing-data warning, just an absence. The "In
progress" list on /papers/ had been empty for exactly this reason.

It is also a build-breaker waiting to happen. On Hugo 0.123 that ERROR is
logged and the build continues; on current Hugo the same line ends with
`Error: error building site: logged 1 error(s)` and exits non-zero. Verified
both ways.

THE SHAPE THIS SETTLES ON.

    data-src/*.csv    the spreadsheets. Edit these. Source of truth.
    data/*.yaml       generated, committed, and what Hugo actually reads.

Keeping the CSVs means keeping the way these are actually maintained — opened
in a spreadsheet, sorted, a row added. Generating YAML beside them means Hugo
gets the array-of-maps it needs, and the templates work unchanged:
`where . "Status" "In Progress"` and `.Title` behave exactly as written.

The generated YAML is committed rather than built in CI on purpose. It means a
clone builds without running anything first, and the deploy workflow needs no
new step — which matters because a Pages build that depends on a generation
step is a build that fails the day the step is skipped.

EVERY VALUE STAYS A STRING. A CSV cell has no type, and letting YAML infer one
would quietly turn a year into an integer, `NA` into null, and a DOI beginning
with `10.` into a float. Comparisons in templates are string comparisons, so
the strings are what keep them working.

Files whose names start with `_` are skipped. They are working files that
happen to be spreadsheets — `_abstracts_for_review.csv` is a review scratchpad,
not something the site should publish.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: missing PyYAML.  pip3 install pyyaml", file=sys.stderr)
    raise SystemExit(2)

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "data-src"
OUT = REPO / "data"

HEADER = ("# GENERATED by scripts/build_data.py from {src} — do not edit.\n"
          "# Edit the spreadsheet and re-run:  python3 scripts/build_data.py\n")


def rows_of(path: Path) -> list[dict]:
    """CSV -> list of dicts, every value a stripped string.

    Blank rows are dropped: a trailing empty line is what a spreadsheet leaves
    behind on export, and it would otherwise become a record with every field
    empty and a title of "" sitting at the bottom of a published list.
    """
    with path.open(encoding="utf-8-sig", newline="") as fh:
        out = []
        for r in csv.DictReader(fh):
            rec = {(k or "").strip(): (v or "").strip()
                   for k, v in r.items() if k}
            if any(rec.values()):
                out.append(rec)
        return out


def render(path: Path) -> str:
    body = yaml.safe_dump(rows_of(path), allow_unicode=True, sort_keys=False,
                          default_flow_style=False, width=100)
    return HEADER.format(src=path.name) + body


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate data/*.yaml from the spreadsheets in data-src/.")
    ap.add_argument("--check", action="store_true",
                    help="fail if any generated file is out of date; write nothing")
    a = ap.parse_args(argv)

    if not SRC.is_dir():
        print(f"no {SRC.relative_to(REPO)}/ directory — nothing to build")
        return 0

    sources = sorted(p for p in SRC.glob("*.csv") if not p.name.startswith("_"))
    if not sources:
        print(f"no spreadsheets in {SRC.relative_to(REPO)}/")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    stale, wrote = [], []
    for src in sources:
        dest = OUT / f"{src.stem}.yaml"
        text = render(src)
        if dest.exists() and dest.read_text(encoding="utf-8") == text:
            print(f"  = {dest.relative_to(REPO)}  ({len(rows_of(src))} rows, current)")
            continue
        if a.check:
            stale.append(dest.relative_to(REPO))
            continue
        dest.write_text(text, encoding="utf-8")
        wrote.append(dest.relative_to(REPO))
        print(f"  + {dest.relative_to(REPO)}  ({len(rows_of(src))} rows)")

    # A CSV still sitting in data/ is the original bug, so say so rather than
    # letting it be rediscovered from a build log.
    leftovers = sorted(OUT.glob("*.csv"))
    if leftovers:
        print(f"\n  WARNING: {len(leftovers)} CSV file(s) are still in data/ and "
              f"Hugo will log an error for each:")
        for p in leftovers:
            print(f"      {p.relative_to(REPO)}")
        print(f"  Move them to {SRC.relative_to(REPO)}/ (or out of the repo if "
              f"they are working files).")

    if a.check and stale:
        print(f"\n  OUT OF DATE: {len(stale)} generated file(s) do not match "
              f"their spreadsheet:")
        for p in stale:
            print(f"      {p}")
        print("  Run:  python3 scripts/build_data.py")
        return 1
    if a.check:
        print("\n  all generated data files are current")
    elif not wrote:
        print("\n  nothing to do — everything was already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
